### ISSUE TITLE
SWF20: Nuevo ícono en la lista de reserva si el hotel esta confirmado.

### ISSUE THREAD

**Issue by boomideapro** [boomideapro/logisticaintegral#12]
┆Attachments: <a href="https:&#x2F;&#x2F;trello-attachments.s3.amazonaws.com&#x2F;59de59e4e6d59a937c8d6ed8&#x2F;5ab956b26488c25d7ec5eba1&#x2F;c94498c5258d1eec14d450d7e9f98f13&#x2F;icono_de_hotel_confirmado.png">icono de hotel confirmado.png</a>

**Comment by boomideapro** [comment]
➤ Alfredo Contreras commented:

se incorporaron SWF 18 y 20 en esta tarea

**Comment by dmoreno1828** [comment]
Actividad Lista
