### ISSUE TITLE
SWF18: Nueva función de notificar al hotel

### ISSUE THREAD

**Issue by boomideapro** [boomideapro/logisticaintegral#13]
Nueva función de notificar al hotel si se edita o elimina un servicio hotelero, asi como ya se notifica cuando se agrega un servicio hotelero al proveedor.

**Comment by boomideapro** [comment]
➤ Alfredo Contreras commented:

este requerimiento fue incorporado al SWF20, ya que estan muy conectadas ambas tareas.

**Comment by dmoreno1828** [comment]
Listo
