### ISSUE TITLE
SWF17: Cuentas por pagar de Holería completo

### ISSUE THREAD

**Issue by boomideapro** [boomideapro/logisticaintegral#14]
┆Attachments: <a href="https:&#x2F;&#x2F;trello-attachments.s3.amazonaws.com&#x2F;59de59e4e6d59a937c8d6ed8&#x2F;5ab9567a831187ad599c2c2e&#x2F;a4af6c0b29566b17d3011301268e36be&#x2F;filtros_en_cuentas_por_pagar.png">filtros en cuentas por pagar.png</a> | <a href="https:&#x2F;&#x2F;trello-attachments.s3.amazonaws.com&#x2F;59de59e4e6d59a937c8d6ed8&#x2F;5ab9567a831187ad599c2c2e&#x2F;7e64ebc40e5ddcd49d51d56fef1985a7&#x2F;cuetas_por_pagar_logistica.png">cuetas por pagar logistica.png</a>

**Comment by dmoreno1828** [comment]
Actividad Finalizada
