### ISSUE TITLE
SWF014: Escaneo de multiples vouchers con un solo click en Recepción de los mismos una vez que fue liquidado por el proveedor

### ISSUE THREAD

**Issue by boomideapro** [boomideapro/logisticaintegral#15]

**Comment by boomideapro** [comment]
➤ E Carrasquero commented:

@abonilla7 hay retraso de 1 dia para la entrega

**Comment by boomideapro** [comment]
➤ Alfredo Contreras commented:

no importa el sitio del boton. hay premura equipo de parte del cliente

**Comment by boomideapro** [comment]
➤ Alfredo Contreras commented:

Escaneo de multiples vouchers con un solo click en Recepción de los mismos una vez que fue liquidado por el proveedor

**Comment by dmoreno1828** [comment]
Listo, la funcionalidad
